spring.application.name=base66
spring.config.import=optional:file:.env[.properties]
opencode.base-url=${OPENCODE_BASE_URL}

app.auth.users[0].username=user1
app.auth.users[0].password=pass1
app.auth.users[0].roles=USER

app.auth.users[1].username=user2
app.auth.users[1].password=pass2
app.auth.users[1].roles=USER

app.auth.jwt-secret=${APP_AUTH_JWT_SECRET}
app.auth.jwt-expiration-seconds=${APP_AUTH_JWT_EXPIRATION_SECONDS}
